BOX         = "alvistack/ubuntu-24.04"
MASTER      = "lotrapanS"
WORKER      = "lotrapanSW"
IP_MASTER   = "192.168.56.110"
IP_WORKER   = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    echo "#{IP_MASTER} #{MASTER}" | tee -a /etc/hosts
    echo "#{IP_WORKER} #{WORKER}" | tee -a /etc/hosts
  SHELL

  config.vm.define MASTER do |master|
    master.vm.hostname = MASTER
    master.vm.network "private_network", ip: IP_MASTER
    master.vm.network "forwarded_port", guest: 22, host: 2242, id: "ssh"

    master.vm.provision "shell", path: "scripts/k3s_master.sh"

    master.vm.provider "libvirt" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.cpu_mode = "host-passthrough"
      vb.graphics_type = "none"
    end
  end

  config.vm.define WORKER do |agent|
    agent.vm.hostname = WORKER
    agent.vm.network "private_network", ip: IP_WORKER
    agent.vm.network "forwarded_port", guest: 22, host: 2242, id: "ssh"

    agent.vm.provision "shell", path: "scripts/k3s_agent.sh", args: [IP_MASTER, IP_WORKER]

    agent.vm.provider "libvirt" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.cpu_mode = "host-passthrough"
      vb.graphics_type = "none"
    end
  end

end
